[package]
name = "ml"
version = "0.1.0"
authors = ["Kevin <kevinarmandzakka@gmail.com>"]
edition = "2018"

[dependencies]
ndarray = "0.12.1"
ndarray-rand = "0.9.0"
rand = "0.6.5"
npy = "0.4.0"
npy-derive = "0.4"
